name: Mirror to GitLab

on:
  push:
    branches:
      - '*'

jobs:
  mirror:
    runs-on: self-hosted
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Push all branches and tags to GitLab
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "lelandkr@ornl.gov"
          
          # Add GitLab remote using the GitLab username and token
          git remote set-url gitlab https://$GITLAB_USERNAME:$GITLAB_TOKEN@gitlab.ccs.ornl.gov/ua/olcf-user-docs-internal-mirror.git
          
          # Push all branches and tags to GitLab (but do not overwrite GitLab-only branches)
          git push --all gitlab
          git push --tags gitlab
